// Code generated by "stringer -type=itemType"; DO NOT EDIT

package main

import "fmt"

const _itemType_name = "itemErroritemEOFitemNumberitemTextitemStartMultilineCommentitemMultilineCommentitemEndMultilineCommentitemStartDocstringLineCommentitemDocstringLineCommentitemStartLineCommentitemLineCommentitemIdentifieritemWhitespaceitemBuiltinFunctionitemOpenBracketitemCloseBracketitemSemicolonitemPipeitemOpenParenitemCloseParenitemSingleQuoteitemDoubleQuoteitemStringitemOpenCurlyitemCloseCurlyitemNewlinekeyword_beginningkeywordIfkeywordElsekeywordRepeatkeywordWithkeywordWhilekeywordDokeywordUntilkeywordSwitchkeywordCasekeywordDefaultkeywordBreakkeywordContinuekeywordExitkeywordVarkeywordDivkeywordModkeywordOtherkeywordSelfkeywordAllkeywordNoonekeywordEnumkeywordUndefinedkeywordTruekeywordFalsekeywordAndkeywordOrkeywordXorkeywordNotkeywordStringkeywordRealkeywordArraykeywordBooleankeywordPtrkeyword_endop_beginningcompEqcompNEqcompLtEqcompGtEqopOrEqopXorEqopAddEqopSubEqopIncopDecop_multichar_endopEqopAddopSubopMulopDivopModopXorop_end"

var _itemType_index = [...]uint16{0, 9, 16, 26, 34, 59, 79, 102, 131, 155, 175, 190, 204, 218, 237, 252, 268, 281, 289, 302, 316, 331, 346, 356, 369, 383, 394, 411, 420, 431, 444, 455, 467, 476, 488, 501, 512, 526, 538, 553, 564, 574, 584, 594, 606, 617, 627, 639, 650, 666, 677, 689, 699, 708, 718, 728, 741, 752, 764, 778, 788, 799, 811, 817, 824, 832, 840, 846, 853, 860, 867, 872, 877, 893, 897, 902, 907, 912, 917, 922, 927, 933}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
